# VALIDAÇÃO DOS SPLINES CÚBICOS

In [1]:
import numpy as np    
import polars as pl    
from Classes.Splines import CubicSpline as CS_MY
from scipy.interpolate import CubicSpline as CS_SP


#### FUNÇÃO DE TESTE

In [2]:
def f(t):
    return 4*t**2 + 2*t + 5

def f_dot(t):
    return 8*t + 2


#### CONSTRUÇÃO DO SPLINE

In [3]:
t_train = np.arange(0, 5, 0.5)
y_train = f(t_train)
cs_sp = CS_SP(t_train, y_train)
cs_my = CS_MY(t_train, y_train, f_dot(t_train[0]), f_dot(t_train[-1]), bc_type= 'clamped')

[ 24.  36.  48.  60.  72.  84.  96. 108.] [12. 24. 36. 48. 60. 72. 84. 96.]


#### TESTE DO SPLINE

In [4]:
t_test = np.arange(0, 4, 0.2)
y_test = f(t_test)
y_spline_my = cs_my(t_test)
y_spline_sp = cs_sp(t_test)

#### SCIPY

In [5]:
y_spline_sp - y_test

array([ 0.00000000e+00,  0.00000000e+00, -8.88178420e-16,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -3.55271368e-15,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.42108547e-14])

### AUTORAL

In [6]:
y_spline_my - y_test

array([ 0.00000000e+00,  0.00000000e+00, -8.88178420e-16,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -3.55271368e-15,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00])